const blogCategories:string[] = [
    'All',
    'Technology',
    'Science',
    'Programming',
    'Web Development',
    'Design',
    'Travel',
    'Food',
    'Health',
    'Fitness',
    'Lifestyle',
    'Finance',
    'Business',
    'Entertainment',
    'Books',
    'Movies',
    'Music',
    'Sports',
    'Education',
    'Art',
    'Photography',
    'Fashion',
    'Beauty',
    'DIY',
    'Home Decor',
    'Gardening',
    'Parenting',
    'Pets',
    'Relationships',
    'Self Improvement',
    'Motivation',
  ];
  
  export default blogCategories;
  